import Link from 'next/link';
import { redirect } from 'next/navigation';
import { AppShell } from '@/components/layout/app-shell';
import { Card, CardDescription, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { buttonVariants } from '@/components/ui/button';
import { getAccess } from '@/src/lib/access';
import { listAllReports } from '@/src/lib/access/admin';
import { formatDateTimeMelbourne, formatMoney } from '@/src/lib/utils';
import { PURPOSE_LABELS, type CasePurpose } from '@/src/lib/db/types';

export const metadata = { title: 'Admin · All reports' };
export const dynamic = 'force-dynamic';

export default async function AdminReportsPage({ searchParams }: { searchParams: Promise<{ user?: string }> }) {
  let access;
  try {
    access = await getAccess();
  } catch {
    redirect('/login?next=/admin/reports');
  }
  if (!access.can.viewAllReports) redirect('/dashboard');
  const { user: filter } = await searchParams;

  let reports: Awaited<ReturnType<typeof listAllReports>> = [];
  let error: string | null = null;
  try {
    reports = await listAllReports(access.supabase);
  } catch (e) {
    error = e instanceof Error ? e.message : 'Could not load reports';
  }
  const owners = [...new Set(reports.map((r) => r.owner_label))].sort();
  const shown = filter ? reports.filter((r) => r.owner_label === filter) : reports;

  return (
    <AppShell>
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="text-2xl font-semibold">All reports</h1>
          <p className="text-sm text-muted">Every report generated by every user. Reports are immutable snapshots; download gives the stored PDF.</p>
        </div>
        <Link href="/admin" className={buttonVariants({ variant: 'secondary' })}>
          Users
        </Link>
      </div>
      {error ? (
        <Card className="mt-6 border-red-200 bg-red-50">
          <CardTitle>Could not load reports</CardTitle>
          <CardDescription>{error}</CardDescription>
        </Card>
      ) : null}
      {owners.length > 1 ? (
        <nav aria-label="Filter by user" className="mt-4 flex flex-wrap gap-2 text-sm">
          <Link href="/admin/reports" className={buttonVariants({ variant: filter ? 'secondary' : 'default', size: 'sm' })}>
            Everyone
          </Link>
          {owners.map((o) => (
            <Link key={o} href={`/admin/reports?user=${encodeURIComponent(o)}`} className={buttonVariants({ variant: filter === o ? 'default' : 'secondary', size: 'sm' })}>
              {o}
            </Link>
          ))}
        </nav>
      ) : null}
      <div className="mt-4 overflow-x-auto rounded-lg border border-border bg-card">
        <table className="w-full text-sm">
          <thead className="bg-slate-50 text-left text-xs text-muted">
            <tr>
              <th className="px-4 py-2">Generated</th>
              <th className="px-4 py-2">User</th>
              <th className="px-4 py-2">Profile</th>
              <th className="px-4 py-2">Year</th>
              <th className="px-4 py-2">Result</th>
              <th className="px-4 py-2">Status</th>
              <th className="px-4 py-2">PDF</th>
            </tr>
          </thead>
          <tbody>
            {shown.map((r) => (
              <tr key={r.id} className="border-t border-border">
                <td className="px-4 py-2 whitespace-nowrap">{formatDateTimeMelbourne(r.created_at)}</td>
                <td className="px-4 py-2">{r.owner_label}</td>
                <td className="px-4 py-2">{r.profile_name}</td>
                <td className="px-4 py-2 whitespace-nowrap">
                  {r.financial_year}
                  <span className="block text-xs text-muted">{PURPOSE_LABELS[r.purpose as CasePurpose] ?? r.purpose}</span>
                </td>
                <td className="px-4 py-2 whitespace-nowrap">
                  {r.result_cents === null ? '—' : `${r.result_cents < 0 ? 'Debt' : 'Refund'} ${formatMoney(Math.abs(r.result_cents))}`}
                  {r.confidence ? <span className="block text-xs text-muted">confidence {r.confidence}</span> : null}
                </td>
                <td className="px-4 py-2">
                  <Badge tone={r.is_final ? 'success' : 'neutral'}>{r.is_final ? 'Final' : 'Draft'}</Badge>
                  {r.rule_set_version ? <span className="block text-xs text-muted">rules {r.rule_set_version}</span> : null}
                </td>
                <td className="px-4 py-2 whitespace-nowrap">
                  <a href={`/api/admin/reports/${r.id}/pdf`} className="underline">
                    Download
                  </a>
                </td>
              </tr>
            ))}
            {shown.length === 0 && !error ? (
              <tr>
                <td className="px-4 py-3 text-muted" colSpan={7}>
                  No reports yet.
                </td>
              </tr>
            ) : null}
          </tbody>
        </table>
      </div>
    </AppShell>
  );
}
